version: '3.9'

services:
  python:
    command: python3 /root/code/app.py
    image: thamakorn/ait-ml-python:a2.2
    environment:
      - HOST=0.0.0.0
      - PORT=80
    # This is important for asking Traefik to use your container.
    labels:
      # Allow Traefik to talk with your service
      - traefik.enable=true
      # Tell Traefik to use port 80
      - traefik.http.services.python-st124481.loadbalancer.server.port=80
      # This config you domain name. By default, your subdomain is python-st124481
      # If you which to change the subdomain name, you uncomment the below configuration
      - traefik.http.routers.python-st124481.rule=Host(`st124481.ml2023.cs.ait.ac.th`)
      # Below is for enable SSL.
      - traefik.http.routers.python-st124481.tls=true
      - traefik.http.routers.python-st124481.tls.certresolver=production
      - traefik.http.routers.python-st124481.entrypoints=websecure
    # This define network. You would need to keep it like this.
    networks:
      - default
      - traefik_default
      
  mlflow:
    image: thamakorn/ait-ml-mlflow:a2.2
    # This is important for asking Traefik to use your container.
    labels:
      # Allow Traefik to talk with your service
      - traefik.enable=true
      # Tell Traefik to use port 80
      - traefik.http.services.mlflow-st124481.loadbalancer.server.port=5000
      # This config you domain name. By default, your subdomain is mlflow-st124481
      # If you which to change the subdomain name, you uncomment the below configuration
      #- traefik.http.routers.mlflow-st124481.rule=Host(`st124481.ml2023.cs.ait.ac.th`)
      # Below is for enable SSL.
      - traefik.http.routers.mlflow-st124481.tls=true
      - traefik.http.routers.mlflow-st124481.tls.certresolver=production
      - traefik.http.routers.mlflow-st124481.entrypoints=websecure
    # This define network. You would need to keep it like this.
    networks:
      - default
      - traefik_default
    


# Keep it like this too.
networks:
  default:
  traefik_default:
    external: true