version: '3.9'

services:
  python:
    command: python3 /root/code/app.py
    image: thamakorn/ait-ml-python:a3
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: python.Dockerfile
    ports:
      - 9001:80
    volumes:
      - ./code:/root/code
      - .vscode-server:/root/.vscode-server
    environment:
      - HOST=0.0.0.0
      - PORT=80
      
  mlflow:
    image: thamakorn/ait-ml-mlflow:a3
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: mlflow.Dockerfile
    # volumes:
    #   - ./_mlflow:/mlflow
    ports:
      - 5000:5000